alarm_delivery:
  email_to: ''
  smtp_host: smtp.gmail.com
  smtp_password: ''
  smtp_port: 587
  smtp_user: ''
  telegram_bot_token: ''
  telegram_chat_id: ''
  telegram_contacts: []
  use_email: false
  use_sound: true
  use_telegram: false
data_dir: ''
global_threshold: 1.0e+37
parallel_measurement: false
