- alias: 2636A
  class_name: core.keithley_2636a.Keithley2636A
  interface_type: LAN
  address: 192.168.0.10
  mac_address: 00-60-1A-00-92-33
  extra_params: {}
- alias: ITC
  class_name: core.generic_scpi.GenericSCPIInstrument
  interface_type: LAN
  address: 192.168.0.5
  mac_address: 00-10-A5-20-30-4A
  port: 7020
  extra_params: {}
- alias: IPS
  class_name: core.generic_scpi.GenericSCPIInstrument
  interface_type: LAN
  address: 192.168.0.3
  mac_address: ''
  port: 7020
  extra_params: {}
- alias: M81
  class_name: core.m81.M81Instrument
  interface_type: LAN
  address: 192.168.0.9
  mac_address: 00-19-B8-0B-06-F5
  port: 7777
  extra_params: {}
- alias: SIGGEN
  class_name: core.m81.M81Instrument
  interface_type: LAN
  address: 192.168.0.7
  mac_address: 00-90-B8-1B-D9-F8
  extra_params: {}
- alias: VNA
  class_name: core.m81.M81Instrument
  interface_type: LAN
  address: 192.168.0.20
  mac_address: 00-30-64-01-78-0A
  extra_params: {}
- alias: SR830
  class_name: core.m81.M81Instrument
  interface_type: LAN
  address: 192.168.0.xx
  mac_address: ''
  extra_params: {}
