sweep_values:
- alias: 2636A
  description: write_smua_voltage
  cmd_set: smua.source.levelv={v}
  paired_read_cmd: reading=smua.measure.v()print(reading)
  figure_axis: target_smua_voltage
  unit: V
  safety_steps: 10
  safety_interval_ms: 5.0
- alias: 2636A
  description: write_smub_voltage
  cmd_set: smub.source.levelv={v}
  paired_read_cmd: reading=smub.measure.v()print(reading)
  figure_axis: target_smub_voltage
  unit: V
  safety_steps: 10
  safety_interval_ms: 5.0
measurements:
- alias: 2636A
  description: read_smua_current
  resolved_cmd: print(smua.measure.i())
  figure_axis: smua_current
  unit: A
- alias: 2636A
  description: read_smub_current
  resolved_cmd: print(smub.measure.i())
  figure_axis: smub_current
  unit: A
- alias: 2636A
  description: read_smua_voltage
  resolved_cmd: print(smua.measure.v())
  figure_axis: smua_voltage
  unit: V
- alias: 2636A
  description: read_smub_voltage
  resolved_cmd: print(smub.measure.v())
  figure_axis: smub_voltage
  unit: V
write_cmds: []
second_sweep_channels: []
