sweep_values:
- alias: 2636A
  description: write_smua_voltage
- alias: 2636A
  description: write_smub_voltage
measurements:
- alias: 2636A
  description: read_smua_current
- alias: 2636A
  description: read_smub_current
- alias: 2636A
  description: read_smua_voltage
- alias: 2636A
  description: read_smub_voltage
write_cmds: []
second_sweep_channels:
- alias: 2636A
  description: write_smua_voltage
- alias: 2636A
  description: write_smub_voltage
